version: '3'
services:
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: patata
      MYSQL_DATABASE: granier
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"        
  frontend:
    image: nginx
    container_name: frontend
    volumes: 
      - ./htmls:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates/cert.crt:/etc/nginx/ssl/cert.crt
      - ./nginx/certificates/private.key:/etc/nginx/ssl/private.key
    ports: 
      - "80:80"
      - "443:443"
  api:
    build: api/.
    volumes:
      - ./api/out:/app/out
    ports:
      - "5000:5000"

